### ISSUE TITLE
Yahoo Wether API에서 "City not found" 에러

### ISSUE THREAD

**Issue by truhojun** [jongh0/MTree#1]
Yahoo Wether API에서 "Hanoi"의 날씨를 조회할때
"City not found" 에러가 발생합니다.
"Hanoi"이외 다른 지역은 잘되네요
City List는 어디서 가져와야 하나요?
List 조회해서 전지역 날씨 Query하는건 어떨까요?

**Comment by jongh0** [comment]
City List 뽑는 방법을 몰라서 하나씩 Query 날려서 리턴 있는 것들로 만들었음 ㅋ
Hanoi도 잘 됐었는데 바뀐건가 모르겠네
City List 뽑을 수 있으면 가장 좋을 듯..
